=== ahead-fop/frabbuccino/base/ajc-harness/tests/ajcTestSuite.dtd
<!-- this defines a DOCTYPE for a suite of ajc tests -->
<!-- element-component mappings are in org.aspectj.testing.xml.AjcSpecXmlReader -->
<!-- element names are determined by the component XMLNAME static variable -->

   <!ELEMENT suite (ajc-test*)>
   <!ATTLIST suite suiteDir CDATA #IMPLIED >

   <!ELEMENT ajc-test (compile, (compile | inc-compile | run)*)>
   <!ATTLIST ajc-test title CDATA #REQUIRED >
   <!ATTLIST ajc-test dir CDATA #REQUIRED >
   <!ATTLIST ajc-test pr CDATA #IMPLIED >
   <!ATTLIST ajc-test keywords CDATA #IMPLIED >
   <!ATTLIST ajc-test comment CDATA #IMPLIED >

   <!ELEMENT compile (dir-changes*,file*,(abcmessage | message)*)>
   <!ATTLIST compile staging CDATA #IMPLIED >
   <!ATTLIST compile badInput CDATA #IMPLIED >
   <!ATTLIST compile files CDATA #IMPLIED >
   <!ATTLIST compile reuseCompiler CDATA #IMPLIED >
   <!ATTLIST compile includeClassesDir CDATA #IMPLIED >
   <!ATTLIST compile argfiles CDATA #IMPLIED >
   <!ATTLIST compile aspectpath CDATA #IMPLIED >
   <!ATTLIST compile classpath CDATA #IMPLIED >
   <!ATTLIST compile extdirs CDATA #IMPLIED >
   <!ATTLIST compile options CDATA #IMPLIED >
   <!ATTLIST compile sourceroots CDATA #IMPLIED >

   <!ELEMENT inc-compile (dir-changes*,message*)>
   <!ATTLIST inc-compile tag CDATA #REQUIRED >
   <!ATTLIST inc-compile fresh CDATA #IMPLIED >

   <!ELEMENT run (dir-changes*,message*)>
   <!ATTLIST run class CDATA #REQUIRED >
   <!ATTLIST run skipTester CDATA #IMPLIED >
   <!ATTLIST run vm CDATA #IMPLIED >
   <!ATTLIST run options CDATA #IMPLIED >
   <!ATTLIST run errStreamIsError CDATA #IMPLIED >
   <!ATTLIST run outStreamIsError CDATA #IMPLIED >

   <!ELEMENT file (#PCDATA)>
   <!ATTLIST file path CDATA #IMPLIED >

   <!ELEMENT message (source*)>
   <!ATTLIST message kind (abort | fail | error | warning | info | Xlint) #REQUIRED >
   <!ATTLIST message line CDATA #IMPLIED >
   <!ATTLIST message text CDATA #IMPLIED >
   <!ATTLIST message file CDATA #IMPLIED >
   <!ATTLIST message details CDATA #IMPLIED >

   <!ELEMENT abcmessage (source*)>
   <!ATTLIST abcmessage kind (abort | fail | error | warning | info | Xlint) #REQUIRED >
   <!ATTLIST abcmessage line CDATA #IMPLIED >
   <!ATTLIST abcmessage text CDATA #IMPLIED >
   <!ATTLIST abcmessage file CDATA #IMPLIED >
   <!ATTLIST abcmessage details CDATA #IMPLIED >

   <!ELEMENT source (#PCDATA)>
   <!ATTLIST source line CDATA #IMPLIED >
   <!ATTLIST source file CDATA #IMPLIED >

   <!ELEMENT dir-changes (#PCDATA)>
   <!ATTLIST dir-changes dirToken (classes | run) #IMPLIED >
   <!ATTLIST dir-changes defaultSuffix (.class) #IMPLIED >
   <!ATTLIST dir-changes added CDATA #IMPLIED >
   <!ATTLIST dir-changes removed CDATA #IMPLIED >
   <!ATTLIST dir-changes updated CDATA #IMPLIED >
   <!ATTLIST dir-changes unchanged CDATA #IMPLIED >
   <!ATTLIST dir-changes expDir CDATA #IMPLIED >
   <!ATTLIST dir-changes fastFail CDATA #IMPLIED >

=== ahead-fop/frabbuccino/trunk/base/ajc-harness/tests/ajcTestsFailCompilation.xml
<!DOCTYPE suite SYSTEM "../tests/ajcTestSuite.dtd">

<!--
  known keywords:
 
  knownLimitation     Accepted limitation of current implementation (fails)
  purejava            Sources compile under javac as well
  broken-test         ??
  messages-vary       one of many (usually two) test specs that differ only in 
                      messages expected by the different compilers.
                      Currently ajc 1.0 tests are in ajcTests10.xml,
                      so there may only be one copy marked "messages-vary" here.
  new-messages-vary   like messages-vary, except need to make ajcTest10 variant

  fail-{...}          test fails in some configuration
  fail-unimplmented   eajc throwing "unimplemented" exception
  fail-commandLine    fails in ajc on command line (move to ajcTestsBroken.xml)
  fail-in-eclipse     fail when harness in run from inside eclipse
  fail-publicType     now fixed - no longer presenting error for public type in wrong file

  from-{file}         from original {file}.txt for file in
                      java, bigjava, resolved_1*, 14tests, errors, design, base... 

  incremental-test    uses inc-compile step
  command-error       command-line error test

  knownLimitation-ajctaskCompiler
                      Accepted limitation of the AjcTaskCompilerCommand wrapper
  knownLimitation-ajdeCompiler
                      Accepted limitation of the AJDE CompileCommand wrapper
                      
  poorErrorMessages   test case passes but errors produced by compiler could do with
                      improvement                      
                      
  Test titles:
  
  Titles should be unique and not change, and related tests should have the 
  same title prefix.  This permits us to automatically compare the test results 
  from different versions (and suites), and to see related differences together.
  
  -->

<suite>
    <ajc-test dir="pureJava" title="return;;; is not really legal"
      keywords="from-java,purejava">
        <compile files="ReachableEmpty.java">
            <message kind="error" line="5"/>
            <message kind="error" line="9"/>
            <message kind="error" line="13"/>
            <message kind="error" line="17"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava/innerDefaultConstructors"
      title="Default constructors have same access as their enclosing type"
      keywords="from-java">
        <compile files="pkg1/Main.java,pkg2/Foo.java">
            <message kind="error" line="6"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava" title="A.this exprs match by exact type matching"
      keywords="from-java">
        <compile files="QualifiedThisMatchesExactly.java">
            <message kind="error" line="14"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava"
      title="Implicit this for new inner instance must be avaliable"
      keywords="from-java">
        <compile files="ImplicitThisMissing.java">
            <message kind="error" line="4"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new" title="IOException on windows if nul used as identifier"
      keywords="from-java,purejava">
        <compile files="NulIOException.java">
            <message kind="error" line="12"/>
            <message kind="error" line="14"/>
            <message kind="error" line="17"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new"
      title="NullPointerException (not compiler error) when extending non-static inner class"
      keywords="from-java,purejava">
        <compile files="ExtendInnerCE.java">
            <message kind="error" line="3"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava"
      title="Binops aren't allowed as update stmts in for loops"
      keywords="from-java">
        <compile files="NonStmtInFor.java">
            <message kind="error" line="3"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava" title="invalid numeric literals"
      keywords="from-java">
        <compile files="LiteralsCf.java">
            <message kind="error" line="8"/>
            <message kind="error" line="9"/>
            <message kind="error" line="10"/>
            <message kind="error" line="11"/>
            <message kind="error" line="12"/>
            <message kind="error" line="17"/>
            <message kind="error" line="18"/>
            <message kind="error" line="19"/>
            <message kind="error" line="20"/>
            <message kind="error" line="21"/>
            <message kind="error" line="22"/>
            <message kind="error" line="23"/>
            <message kind="error" line="25"/>
            <message kind="error" line="27"/>
            <message kind="error" line="28"/>
            <message kind="error" line="29"/>
            <message kind="error" line="30"/>
            <message kind="error" line="32"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava" pr="538"
      title="inner types can't have the same simple name as an enclosing type"
      keywords="from-java">
        <compile files="InnerNameConflictsCf.java">
            <message kind="error" line="9"/>
            <message kind="error" line="14"/>
            <message kind="error" line="20"/>
            <message kind="error" line="21"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new" title="Error expected for field of type void"
      keywords="from-java,purejava">
        <compile files="VoidField.java">
            <message kind="error" line="2"/>
            <message kind="error" line="4"/>
            <message kind="error" line="6"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new" title="Error expected for constructor in interfaces"
      keywords="from-java,purejava">
        <compile files="InterfaceConstructor.java">
            <message kind="error" line="2"/>
            <message kind="error" line="6"/>
            <message kind="error" line="8"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new" pr="558"
      title="class name for identifier as String should provoke error"
      keywords="from-java,purejava">
        <compile files="PR558.java">
            <message kind="error" line="4"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new" pr="567"
      title="cyclic interface inheritance not detected if no classes implement the interfaces"
      keywords="from-java,purejava,messages-vary">
        <compile files="CyclicInterfaceInheritance.java" 
               options="!eclipse">
            <message kind="error" line="14"/>
            <message kind="error" line="15"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new" pr="567" title="cyclic class inheritance"
      keywords="from-java,purejava">
        <compile files="CyclicClassInheritance.java">
            <message kind="error" line="11"/>
            <message kind="error" line="12"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava" title="Type names are not expressions on their own"
      keywords="from-java,purejava">
        <compile files="TypeExprErrors.java">
            <message kind="error" line="10"/>
            <message kind="error" line="17"/>
            <message kind="error" line="18"/>
            <message kind="error" line="19"/>
            <message kind="error" line="20"/>
            <message kind="error" line="21"/>
            <message kind="error" line="22"/>
            <message kind="error" line="23"/>
            <message kind="error" line="24"/>
            <message kind="error" line="25"/>
            <message kind="error" line="26"/>
            <message kind="error" line="27"/>
            <message kind="error" line="28"/>
            <message kind="error" line="29"/>
            <message kind="error" line="30"/>
            <message kind="error" line="31"/>
            <message kind="error" line="32"/>
            <message kind="error" line="33"/>
            <message kind="error" line="34"/>
            <message kind="error" line="36"/>
            <message kind="error" line="37"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava/nameConflicts"
      title="type and package name conflicts caught as errors (1)"
      keywords="from-java,purejava">
        <compile files="p1/p2.java,p1/Main1.java,p1/Foo.java,p1/p2/Foo.java">
            <message kind="error" line="3"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new" pr="588" title="Undefined inner class constructor"
      keywords="from-java,purejava">
        <compile files="UndefinedInner.java">
            <message kind="error" line="6"/>
        </compile>
    </ajc-test>

    <ajc-test dir="pureJava"
      title="qualified this must work exactly, not based on subtypes"
      keywords="from-java">
        <compile files="QualifiedThisExactness.java">
            <message kind="error" line="6"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new/packagePrefix" pr="574"
      title="classes that are package prefixes are illegal"
      keywords="from-java,purejava,messages-vary">
        <compile files="p/prefix.java,p/prefix/SomeClass.java"
               options="!eclipse">
            <message kind="error" line="2"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new/introTypeMissing"
      title="CF expected when enclosing class superclass used as this qualifier in inner class"
      keywords="from-java">
        <compile files="TargetClassCF.java,Util.java">
            <message kind="error" line="22"/>
            <message kind="error" line="23"/>
            <message kind="error" line="27"/>
            <message kind="error" line="28"/>
        </compile>
    </ajc-test>

    <ajc-test dir="new"
      title="PR591 compiler error expected when directly calling unimplemented abstract method using super"
      keywords="from-java,purejava">
        <compile files="AbstractMethodCall.java">
            <message kind="error" line="10"/>
        </compile>
    </ajc-test>
